version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
  registration-login:
    build: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - mysql